spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: Your email address here
    password: App password of your email address here
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8082


